### PR TITLE
Add some commonly ignored files to .gitignore

### PR DESCRIPTION
**Pull request by rowillia**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Most of these should really go into your personal global .gitignore, shouldn't they?

**Comment by rowillia** [comment]
@gvanrossum Could go either way, I grabbed most of these from `mypy` and `cpython` 😄 .  Feel free to close out if you feel differently.

**Comment by gvanrossum** [comment]
The larger the project the more junk it accumulates in its .gitignore. Let's start lean.

**Comment by rowillia** [comment]
@gvanrossum No problem, thanks for taking a look!

**Pull request closed without merging**
