### PR TITLE
Add caller func name into type_info.json to make it clear which function is doing wrong

### PR DESCRIPTION
**Pull request by ghost**
## What this pr does

- add caller func name into type_info.json
- this doesn't affect to any original function

## Why I do this

I think this is really necessary in a kind of big project.

Let's think if you have a code like this.

```python
def main():
    print(gcd(15, 10))
    print(gcd(24, 10))
    print(gcd("a", "b"))

def gcd(a, b):
    return a, b
```

This generates type_info like below.

```json
[
    {
        "path": "gcd.py",
        "line": 1,
        "func_name": "main",
        "type_comments": [
            "() -> None"
        ],
        "samples": 1
    },
    {
        "path": "gcd.py",
        "line": 6,
        "func_name": "gcd",
        "type_comments": [
            "(int, int) -> Tuple[int, int]",
            "(str, str) -> Tuple[str, str]"
        ],
        "samples": 3
    }
]
```

Then, you would come up with the idea like "this gcd function must accept only int. Which function uses in wrong way...?".

However, you can't see any information about that. So you need to dig yourself which code was wrong. I spent the most of time on this while using pyannotate.

Now, this pr will show which code screwed up. This will generate type_info like below

```json
[
    {
        "path": "gcd.py",
        "line": 1,
        "func_name": "main",
        "type_comments": [
            "() -> None"
        ],
        "caller_name": [
            ["__main__ : 7"]
        ],
        "samples": 1
    },
    {
        "path": "gcd.py",
        "line": 6,
        "func_name": "gcd",
        "type_comments": [
            "(int, int) -> Tuple[int, int]",
            "(str, str) -> Tuple[str, str]"
        ],
        "caller_name": [
            [
                "gcd.main : 2",
                "gcd.main : 3"
            ],
            ["gcd.main : 4"]
        ],
        "samples": 3
    }
]
```

As you see, you can understand `(str, str)` is called by `"gcd.main : 4"` easily.

## remarks

I submitted Contributor License Agreement.

### CODE REVIEW

**Comment by ghost** [comment]
Fix https://github.com/dropbox/pyannotate/issues/115

**Comment by ulwlu** [comment]
@msullivan / @JukkaL 
hi, this repo doesn't seem to be reviewed actively, so I'm sorry but I wanted to mention you. I would be happy if you could review it when you have time.

**Comment by ghost** [comment]
@gvanrossum 

Sorry if I shouldn't mention you since you are not in dropbox now, but I just love to hear reviews of this pr.

I really love this project but this doesn't seem to be reviewed actively.

**Comment by gvanrossum** [comment]
You're going to have to find a new maintainer, sorry.

**Pull request closed without merging**
