### PR TITLE
Fix a small mistake in the README

### PR DESCRIPTION
**Pull request by bluebird75**
Words pause() and resume() were exchanged creating some confusion:

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks! Sorry for the confusion. The API is, frankly, confusing -- maybe it should be renamed to start()/stop().

**Comment by bluebird75** [comment]
Indeed, that would make more sense to everybody.

**Comment by gvanrossum** [comment]
Wanna create a PR?

**Comment by bluebird75** [comment]
Yes, I'll look into this.

**Pull request merged**
