### PR TITLE
Include license and examples in tarballs

### PR DESCRIPTION
**Pull request by sebix**
include license and docs/examples

### CODE REVIEW

**Comment by gvanrossum** [comment]
I can merge this now since it's such a small item, but can you please fill out the Dropbox CLA at https://opensource.dropbox.com/cla/.

**Comment by sebix** [comment]
The contribution is under the Apache 2.0 license, as all the content is.

**Comment by gvanrossum** [comment]
Go tell it to our lawyers.

**Comment by gvanrossum** [comment]
(If you don't want to sign it, go ahead and let us know. Your current response is ambiguous and does not help anyone.)

**Comment by sebix** [comment]
> If you don't want to sign it, go ahead and let us know.

I won't and I don't see a reason for it.

**Comment by gvanrossum** [comment]
Then don't bother contributing further. Dropbox's lawyers won't let me
accept contributions whose contributor hasn't signed the CLA. Sorry

**Comment by gvanrossum** [comment]
(To be clear you can still file bugs. You can even leave detailed
instructions on how to fix them. We just can't use any code you send your
way.)

**Pull request closed without merging**
